WEB/WebSoccer/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebSoccer.Models
{
    public class Category
    {
        public Int32 Id { get; set; }

        public String Name { get; set; }
    }
}

WEB/WebSoccer/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebSoccer.BusinessLayer.Filters;
using WebSoccer.Models;
using WebSoccer.Repository;

namespace WebSoccer.Controllers
{
    [AuthenticateAdmin]
    public class CategoryController : Controller
    {
        readonly AllRepository _repository = new AllRepository();


        // GET: /Category/
        public ActionResult Index()
        {
            List<Category> categoryList = _repository.GetCategories();
            return View(categoryList);
        }

        public ActionResult MenuPartial()
        {
            List<Category> categoryList = _repository.GetCategories();
            ViewBag.menu = categoryList;
            return PartialView("_MenuPartial");
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (_repository.AddCategory(category) > 0)
            {
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Edit(int id)
        {
            if (id > 0)
            {
                Category category = _repository.GetCategory(id);
                if (category != null)
                {
                    return View(category);
                }
                else
                {
                    return HttpNotFound();
                }
            }
            return new HttpNotFoundResult();
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (_repository.UpdateCategory(category) > 0)
            {
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public ActionResult Delete(int id)
        {
            if (_repository.DeleteCategory(id) > 0)
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

WEB/WebSoccer/Views/Category/Create.cshtml
@model WebSoccer.Models.Category

@{
    ViewBag.Title = "Create";
}




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg">Add</button>
                </div>
            </div>
        </div>
    </div>
}

WEB/WebSoccer/Views/Category/Edit.cshtml
@model WebSoccer.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name)
                </div>
            </div>
        </div>

       


        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-lg">Edit</button>
                </div>
            </div>
        </div>
    </div>
}

WEB/WebSoccer/Views/Category/Index.cshtml
@model IEnumerable<WebSoccer.Models.Category>

@{
    ViewBag.Title = "Index";
}



<a href="@Url.Action("Create", "Category")" class="btn btn-success">
    <span class="glyphicon glyphicon-plus">
    </span>
    Yeni
</a>
<br/>
<br/>
<table class="table table-bordered table-striped datatable">
    <thead>
        <tr>
            <th>
               Categories
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
{
    <tr>
    <td>
         @Html.ActionLink(Html.DisplayFor(model => item.Name).ToString(), "Index", new {controller = "News", id = item.Id})
    </td>
               
                <td>

                    <a href="@Url.Action("Edit", "Category", new { id = item.Id})" class="btn btn-primary">
                        <span class="glyphicon glyphicon-pencil"></span>
                        Edit
                    </a>
                    @Html.ActionLink("Delete", "Delete", "Category", new { id = item.Id }, new { @class = "btn btn-info" })
                </td>
            </tr>
        }
    </tbody>

</table>

WEB/WebSoccer/Views/Category/_MenuPartial.cshtml
       @foreach (var item in ViewBag.menu)
       {
           <a href="@Url.Action("Index", "News", new {id = item.Id})">
              @item.Name
           </a>
       }
   